### ISSUE TITLE
Input box in property view not readable

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#47]
When clicking in a property field (e.g. Pad Length) you cannot se the value and what you type as it is cut off:
![grafik](https://github.com/obelisk79/OpenDark/assets/6246609/631d9cc8-a41b-4c09-b042-6fa1b140f646)

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35966 (Git)
Build type: Release
Branch: main
Hash: 7f5d89fa1942fec79222e4d173655744037164dc
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.1
  * CurvedShapes 1.0.5
  * Curves 0.6.23
  * Defeaturing 1.2.2
  * fasteners 0.5.2
  * FEMbyGEN 2.1.0
  * freecad.gears 1.0.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.0
  * woodworking 0.21.2.33771
```

**Comment by furgo16** [comment]
Extract from the [duplicate issue](https://github.com/obelisk79/OpenTheme/issues/60) I filed (sorry):

Classic theme:
![Captura de pantalla de 2024-05-17 06-25-36](https://github.com/obelisk79/OpenTheme/assets/148809153/c5db2cbb-bacd-4852-a2d6-c740f3509816)
From OpenTheme theme:
![Captura de pantalla de 2024-05-17 06-28-30](https://github.com/obelisk79/OpenTheme/assets/148809153/a99f5167-d749-4928-949a-a66f6eb46fe5)

This is the main reason I have not switched to OpenTheme yet: it's awkward to change property values due to the difficulty of reading them.

In the screen capture, notice how the text inside the cell being edited is being clipped in height. The reason might be because the text style is bold.

Is the later platform-dependent, or a recent change in the theme? In @maxwxyz's screenshots the text is not bold, as far as I can tell.

**Comment by maxwxyz** [comment]
it's still present in the latest version.
I am glad my text is not bold as your screenshot is barely legible 
![grafik](https://github.com/obelisk79/OpenTheme/assets/6246609/cdd0b30c-b8bf-4bad-bea4-bcf3fedf8ef0)

**Comment by obelisk79** [comment]
I believe I have resolved this issue. The expression editor icon placement got misaligned and took me a bit to get sorted out.
