### ISSUE TITLE
MacOS: Property background always visible

### ISSUE THREAD

**Issue by maxwxyz** [obelisk79/OpenTheme#83]
In the recent version the background of the property view is always visible, also if there is nothing selected and even when there is no document.
<img width="1660" alt="grafik" src="https://github.com/obelisk79/OpenTheme/assets/6246609/26141455-735a-4830-8d9a-50dc049283ad">
<img width="551" alt="grafik" src="https://github.com/obelisk79/OpenTheme/assets/6246609/23b4f928-5703-40d5-8c07-5c4ff1c6e326">

```
OS: macOS 13.6.7
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37841 (Git)
Build type: Release
Branch: main
Hash: 5f761c758e2a0164b00a7183b9c0cbe32688e123
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * 3DfindIT 1.2.0
  * freecad.gears 1.2.0
  * OpenTheme 2024.6.22
  * CfdOF 1.25.17
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.24
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.19
  * Curves 0.6.39

```

**Comment by maxwxyz** [comment]
@obelisk79 FYI

**Comment by maxwxyz** [comment]
@obelisk79 maybe this is now also fixable with the recent changes in main?

**Comment by obelisk79** [comment]
I am concerned that this is likely an issue that is inherent to Qt and the way overlay is implemented. I'll leave this open for now, but I don't have the slightest idea how I would be able to address this with a theme.

**Comment by cbagwell** [comment]
I've copied the following work around on Ondsel.  If you combine the Tasks and Property view like this then the issue goes away.  Originally, I thought it was just hiding the problem behind that tab but looks like its actually gone.

![image](https://github.com/user-attachments/assets/f6f13c3b-07db-410f-83cb-07b2b4f822fd)

If I keep them combined but both visible, then issue reappears as well.

![image](https://github.com/user-attachments/assets/f7fd9ae7-63cb-4442-bd38-787cbd417bc6)

**Comment by cbagwell** [comment]
I updated to weekly 39127 today (how time flies.  I was using 1.0rc2 thinking it was only 2 weeks old) and now this issue is resolved for me.

I did have to manually wipe out my system.cfg and user.cfg file though as when I updated something went bad with the bar at bottom of screen (everything was duplicated at least 3 times). Using preferences reset option would just crash the app.  But those issues are both unrelated issues. 

Anyways, after manual resetting configs and re-enabling OpenDark and re-appling Preferences, the property view now is invisible when empty.  Thanks to all those involved solving this!
